// The Board's rotating quote / fact. Bundled (no network), and picked from the date and a 30-minute
// slot, so every display in the house shows the same one at the same time.

export type Tidbit = { kind: 'quote'; text: string; by: string } | { kind: 'fact'; text: string }

export const QUOTES: { text: string; by: string }[] = [
  { text: 'Not all those who wander are lost.', by: 'J.R.R. Tolkien' },
  { text: 'All we have to decide is what to do with the time that is given us.', by: 'J.R.R. Tolkien' },
  { text: 'Even the smallest person can change the course of the future.', by: 'J.R.R. Tolkien' },
  { text: 'Imagination is more important than knowledge.', by: 'Albert Einstein' },
  { text: 'The important thing is not to stop questioning.', by: 'Albert Einstein' },
  { text: 'Life is like riding a bicycle. To keep your balance you must keep moving.', by: 'Albert Einstein' },
  { text: 'Look deep into nature, and then you will understand everything better.', by: 'Albert Einstein' },
  { text: 'The only way to have a friend is to be one.', by: 'Ralph Waldo Emerson' },
  { text: 'If I have seen further it is by standing on the shoulders of giants.', by: 'Isaac Newton' },
  { text: 'A journey of a thousand miles begins with a single step.', by: 'Lao Tzu' },
  { text: 'Knowing others is intelligence; knowing yourself is true wisdom.', by: 'Lao Tzu' },
  { text: 'Well done is better than well said.', by: 'Benjamin Franklin' },
  { text: 'Energy and persistence conquer all things.', by: 'Benjamin Franklin' },
  { text: 'Lost time is never found again.', by: 'Benjamin Franklin' },
  { text: 'The more that you read, the more things you will know.', by: 'Dr. Seuss' },
  { text: 'Today you are You, that is truer than true. There is no one alive who is Youer than You.', by: 'Dr. Seuss' },
  { text: "A person's a person, no matter how small.", by: 'Dr. Seuss' },
  { text: 'Unless someone like you cares a whole awful lot, nothing is going to get better.', by: 'Dr. Seuss' },
  { text: 'Oh, the thinks you can think up if only you try!', by: 'Dr. Seuss' },
  { text: 'The good thing about science is that it’s true whether or not you believe in it.', by: 'Neil deGrasse Tyson' },
  { text: 'The universe is under no obligation to make sense to you.', by: 'Neil deGrasse Tyson' },
  { text: 'We are made of star-stuff.', by: 'Carl Sagan' },
  { text: 'Imagination will often carry us to worlds that never were. But without it we go nowhere.', by: 'Carl Sagan' },
  { text: 'Nothing in life is to be feared, it is only to be understood.', by: 'Marie Curie' },
  { text: 'One never notices what has been done; one can only see what remains to be done.', by: 'Marie Curie' },
  { text: 'Though she be but little, she is fierce.', by: 'William Shakespeare' },
  { text: 'What’s in a name? That which we call a rose by any other name would smell as sweet.', by: 'William Shakespeare' },
  { text: 'Hope is the thing with feathers that perches in the soul.', by: 'Emily Dickinson' },
  { text: 'In every walk with nature one receives far more than he seeks.', by: 'John Muir' },
  { text: 'The mountains are calling and I must go.', by: 'John Muir' },
  { text: 'Alone we can do so little; together we can do so much.', by: 'Helen Keller' },
  { text: 'Optimism is the faith that leads to achievement.', by: 'Helen Keller' },
  { text: 'Keep your face to the sunshine and you cannot see a shadow.', by: 'Helen Keller' },
  { text: 'You can’t use up creativity. The more you use, the more you have.', by: 'Maya Angelou' },
  { text: 'Try to be a rainbow in someone’s cloud.', by: 'Maya Angelou' },
  { text: 'Do the best you can until you know better. Then when you know better, do better.', by: 'Maya Angelou' },
  { text: 'Darkness cannot drive out darkness; only light can do that.', by: 'Martin Luther King Jr.' },
  { text: 'The time is always right to do what is right.', by: 'Martin Luther King Jr.' },
  { text: 'I am not afraid of storms, for I am learning how to sail my ship.', by: 'Louisa May Alcott' },
  { text: 'Second star to the right, and straight on till morning.', by: 'J.M. Barrie' },
  { text: 'Why, sometimes I’ve believed as many as six impossible things before breakfast.', by: 'Lewis Carroll' },
  { text: 'It’s no use going back to yesterday, because I was a different person then.', by: 'Lewis Carroll' },
  { text: 'Some day you will be old enough to start reading fairy tales again.', by: 'C.S. Lewis' },
  { text: 'Great things are done by a series of small things brought together.', by: 'Vincent van Gogh' },
  { text: 'Colours are the smiles of nature.', by: 'Leigh Hunt' },
  { text: 'A book is a dream that you hold in your hand.', by: 'Neil Gaiman' },
  { text: 'Reading is to the mind what exercise is to the body.', by: 'Joseph Addison' },
  { text: 'Books are a uniquely portable magic.', by: 'Stephen King' },
  { text: 'What you do makes a difference, and you have to decide what kind of difference you want to make.', by: 'Jane Goodall' },
  { text: 'In the end we will conserve only what we love.', by: 'Baba Dioum' },
  { text: 'The sea, once it casts its spell, holds one in its net of wonder forever.', by: 'Jacques Cousteau' },
  { text: 'No water, no life. No blue, no green.', by: 'Sylvia Earle' },
  { text: 'Philosophy begins in wonder.', by: 'Plato' },
  { text: 'The beginning is the most important part of the work.', by: 'Plato' },
  { text: 'Where words fail, music speaks.', by: 'Hans Christian Andersen' },
  { text: 'Just living is not enough. One must have sunshine, freedom, and a little flower.', by: 'Hans Christian Andersen' },
  { text: 'If you look the right way, you can see that the whole world is a garden.', by: 'Frances Hodgson Burnett' },
  { text: 'I’m so glad I live in a world where there are Octobers.', by: 'L.M. Montgomery' },
  { text: 'Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?', by: 'L.M. Montgomery' },
  { text: 'Curiosity is the wick in the candle of learning.', by: 'William Arthur Ward' },
  { text: 'Equipped with his five senses, man explores the universe around him and calls the adventure Science.', by: 'Edwin Hubble' },
  { text: 'The first principle is that you must not fool yourself, and you are the easiest person to fool.', by: 'Richard Feynman' },
  { text: 'It is not the mountain we conquer, but ourselves.', by: 'Edmund Hillary' },
  { text: 'The best way to cheer yourself up is to try to cheer somebody else up.', by: 'Mark Twain' },
  { text: 'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.', by: 'Dr. Seuss' },
  { text: 'While we teach, we learn.', by: 'Seneca' },
  { text: 'Very little is needed to make a happy life.', by: 'Marcus Aurelius' },
  { text: 'Give me a place to stand, and I will move the earth.', by: 'Archimedes' },
  { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', by: 'Oliver Goldsmith' },
  { text: 'Float like a butterfly, sting like a bee.', by: 'Muhammad Ali' },
  { text: 'You miss 100% of the shots you don’t take.', by: 'Wayne Gretzky' },
  { text: 'When you come to a fork in the road, take it.', by: 'Yogi Berra' },
  { text: 'Champions keep playing until they get it right.', by: 'Billie Jean King' },
  { text: 'Talent wins games, but teamwork and intelligence win championships.', by: 'Michael Jordan' },
  { text: 'Even if you’re on the right track, you’ll get run over if you just sit there.', by: 'Will Rogers' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', by: 'Nelson Mandela' },
  { text: 'Autumn is a second spring when every leaf is a flower.', by: 'Albert Camus' },
  { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', by: 'Thomas Edison' },
  { text: 'To see a world in a grain of sand and a heaven in a wild flower.', by: 'William Blake' },
  { text: 'Look up at the stars and not down at your feet.', by: 'Stephen Hawking' },
  { text: 'That’s one small step for a man, one giant leap for mankind.', by: 'Neil Armstrong' },
  { text: 'Fall seven times, stand up eight.', by: 'Japanese proverb' },
  { text: 'Many hands make light work.', by: 'Proverb' },
]

export const FACTS: string[] = [
  'Octopuses have three hearts and blue blood.',
  'A day on Venus is longer than its whole year.',
  'Bananas are berries, but strawberries are not.',
  'Sharks have been around longer than trees.',
  'Sunlight takes about 8 minutes to reach Earth.',
  'A group of flamingos is called a flamboyance.',
  'Sea otters often hold paws while they sleep so they don’t drift apart.',
  'Wombats make cube-shaped poop.',
  'The Eiffel Tower grows up to about 15 cm taller on hot summer days, as the iron expands.',
  'There are more trees on Earth than stars in the Milky Way.',
  'A bolt of lightning is about five times hotter than the surface of the Sun.',
  'Butterflies taste with their feet.',
  'The word “alphabet” comes from alpha and beta, the first two Greek letters.',
  'Saturn is so light for its size that it’s less dense than water.',
  'Koalas can sleep up to 20 hours a day.',
  'Your heart beats about 100,000 times a day.',
  'Babies are born with around 300 bones; adults have 206, because some fuse together.',
  'Jupiter’s Great Red Spot is a storm bigger than the whole Earth.',
  'Neptune was found using maths before anyone saw it through a telescope.',
  'The Moon drifts about 3.8 cm farther from Earth every year.',
  'Footprints on the Moon could last millions of years, because there’s no wind to blow them away.',
  'A polar bear’s fur is actually see-through, and its skin is black.',
  'A giraffe has seven neck bones, the same number as you.',
  'The blue whale is the largest animal known to have ever lived.',
  'Tiny tardigrades, or “water bears”, have survived being exposed to outer space.',
  'Venus is the hottest planet, even though Mercury is closer to the Sun.',
  'Mount Everest grows a few millimetres taller every year.',
  'The Pacific Ocean covers about a third of Earth’s surface.',
  'Honeybees do a “waggle dance” to tell each other where to find flowers.',
  'An ostrich’s eye is bigger than its brain.',
  'Every dog’s nose print is unique, like a fingerprint.',
  'Owls can’t move their eyes, so they turn their heads up to 270 degrees instead.',
  'A baby kangaroo is called a joey.',
  'Sea stars have no brain and no blood.',
  'Some turtles can breathe through their bottoms.',
  'The word “robot” comes from a Czech word for hard work, and first appeared in a 1920 play.',
  '“Goodbye” started out as “God be with ye”.',
  'The dot over a lowercase i or j is called a tittle.',
  'The word “run” has hundreds of different meanings in the Oxford English Dictionary.',
  '“The quick brown fox jumps over the lazy dog” uses every letter of the alphabet.',
  'Shakespeare is the first known writer to use the words “eyeball” and “bedroom”.',
  'The word “muscle” comes from the Latin for “little mouse”.',
  '“Astronaut” means “star sailor” in Greek.',
  '“Dinosaur” means “terrible lizard”.',
  '“Hippopotamus” means “river horse” in Greek.',
  'Rainbows are really full circles; from the ground we usually see only the top arc.',
  'Almost every snowflake has six sides.',
  'Lightning flashes about 40 to 50 times every second somewhere on Earth.',
  'Thousands of years ago the Sahara was green, with lakes, grasslands and hippos.',
  'Antarctica is the world’s largest desert, because so little snow or rain falls there.',
  'Earth’s inner core is about as hot as the surface of the Sun.',
  'The International Space Station circles Earth about every 90 minutes, so astronauts see around 16 sunrises a day.',
  'Olympus Mons on Mars is about two and a half times as tall as Mount Everest.',
  'A year on Mercury lasts just 88 Earth days.',
  'About a million Earths could fit inside the Sun.',
  'Mars is red because its dust is full of iron oxide: rust.',
  'Pluto is smaller than our Moon.',
  'Uranus spins on its side, like a rolling ball.',
  'Astronauts can grow up to about 5 cm taller in space, because their spines stretch out.',
  'Venus spins backwards compared with most planets, so its Sun rises in the west.',
  'Frogs don’t drink with their mouths; they soak up water through their skin.',
  'Garden snails have thousands of tiny teeth.',
  'Emperor penguin dads keep their egg warm on their feet for about two months.',
  'A peregrine falcon can dive at over 320 km/h (200 mph), faster than any other animal.',
  'Some bamboo can grow almost a metre in a single day.',
  'Some bristlecone pine trees are more than 4,800 years old.',
  'Young sunflowers turn to follow the Sun across the sky.',
  'Some mushrooms glow in the dark.',
  'Your brain uses about a fifth of all your body’s energy.',
  'Fingernails grow faster than toenails.',
  'Sound travels about four times faster in water than in air.',
  'Diamonds and pencil “lead” are both made of carbon.',
  'Axolotls can regrow whole legs.',
  'Seahorse dads are the ones who carry the babies.',
  'Goats have rectangle-shaped pupils.',
  'A shrimp’s heart is in its head.',
  'No two zebras have exactly the same stripes.',
  'Apples float because about a quarter of an apple is air.',
  'Peanuts aren’t nuts: they’re legumes, like peas and beans.',
  'A “googol” is 1 followed by 100 zeros, and a nine-year-old came up with the name.',
]

/** The tidbit for a day (its local calendar date) and a 30-minute `slot` of that day (0-47).
 * Alternates quote / fact, stepping through each list with a stride coprime to its length, so
 * neighbouring slots jump between topics and every entry comes round before any repeats. */
export function tidbitFor(date: Date, slot: number): Tidbit {
  const day = Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000)
  const n = day * 48 + slot
  const i = Math.floor(n / 2)
  if (n % 2 === 0) return { kind: 'quote', ...QUOTES[(i * 37) % QUOTES.length] }
  return { kind: 'fact', text: FACTS[(i * 37) % FACTS.length] }
}
